package com.company.oop.tms.commands.enums;

public enum CommandType {

    CREATEMEMBER,
    SHOWMEMBERS,
    SHOWMEMBERSACTIVITY,
    CREATETEAM,
    SHOWTEAMS,
    SHOWTEAMACTIVITY,
    ADDMEMBERTOTEAM,
    SHOWTEAMMEMBERS,
    CREATEBOARD,
    SHOWTEAMBOARDS,
    SHOWBOARDACTIVITY,
    CREATEBUGINBOARD,
    CREATESTORYINBOARD,
    CREATEFEEDBACKINBOARD,
    CHANGEBUGSTATUS,
    CHANGEBUGSEVERITY,
    CHANGEBUGPRIORITY,
    CHANGESTORYSTATUS,
    CHANGESTORYSIZE,
    CHANGESTORYPRIORITY,
    CHANGEFEEDBACKSTATUS,
    CHANGEFEEDBACKRATING,
    ASSIGNTASK,
    UNASSIGNTASK,
    ADDCOMMENTTOTASK,


}
